surface_position:
  kind: noether.data.preprocessors.normalizers.FieldNormalizer
  strategy: position
  stat_keys:
    min: raw_pos_min
    max: raw_pos_max
  scale: 1000
surface_pressure:
  kind: noether.data.preprocessors.normalizers.FieldNormalizer
  strategy: mean_std
surface_friction:
  kind: noether.data.preprocessors.normalizers.FieldNormalizer
  strategy: mean_std
volume_position:
  kind: noether.data.preprocessors.normalizers.FieldNormalizer
  strategy: position
  stat_keys:
    min: raw_pos_min
    max: raw_pos_max
  scale: 1000
volume_vorticity:
  kind: noether.data.preprocessors.normalizers.FieldNormalizer
  strategy: mean_std
  stat_keys:
    mean: _zero
    std: volume_vorticity_magnitude_mean
volume_velocity:
  kind: noether.data.preprocessors.normalizers.FieldNormalizer
  strategy: mean_std
volume_pressure:
  kind: noether.data.preprocessors.normalizers.FieldNormalizer
  strategy: mean_std
geometry_design_parameters:
  kind: noether.data.preprocessors.normalizers.FieldNormalizer
  strategy: mean_std
inflow_design_parameters:
  kind: noether.data.preprocessors.normalizers.FieldNormalizer
  strategy: mean_std
