kind: noether.modeling.models.AeroTransformer
name: transformer
hidden_dim: 192
transformer_block_config: 
  num_heads: 3
  mlp_expansion_factor: 4
  use_rope: true
depth: 12
optimizer_config: ${optimizer}
data_specs: ${data_specs}
forward_properties:
  - surface_position
  - volume_position
  - surface_features
  - volume_features